name: Run EUCLID Record Attendence

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - uses: browser-actions/setup-chrome@latest

      - name: Install Python dependencies
        run: |
              python -m pip install --upgrade pip
              pip install selenium docopt datetime

      - name: Run euclid.py
        shell: bash
        env:
          EASE_USERNAME: ${{ secrets.EASE_USERNAME }}
          EASE_PASSWORD: ${{ secrets.EASE_PASSWORD }}
          EASE_SECURE_WORD: ${{ secrets.EASE_SECURE_WORD }}
          STUDENT1_ONLINE: ${{ secrets.STUDENT1_ONLINE }}
        run: |
              chmod +x ./euclid.py
              ./euclid.py record_attendance -u "$EASE_USERNAME" -p "$EASE_PASSWORD" -s "$EASE_SECURE_WORD" "$STUDENT1_ONLINE"
